name: Deploy to Staging

on:
  push:
    branches: [ staging ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ia-empreendedor:staging
          
      - name: Deploy to Railway
        uses: bervProject/railway-deploy@main
        with:
          service: ia-empreendedor-staging
          railway_token: ${{ secrets.RAILWAY_TOKEN }} 